[tool.poetry]
name = "parakeet"
version = "0.1.0"
description = "Parquet to CSV command line tool"
authors = ["Alfie Bowman <alfiebowman@protonmail.com>"]
readme = "README.md"
homepage = "github.com/A1fus/parakeet"
repository = "github.com/A1fus/parakeet"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
